# Generated by Django 2.1.3 on 2018-11-26 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('purchase_price', models.CharField(max_length=250)),
                ('selling_price', models.CharField(max_length=250)),
                ('store_box', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('company', models.CharField(max_length=250)),
                ('side_effects', models.CharField(max_length=250)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('quantity_left', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MedicineCategory')),
            ],
        ),
    ]
