# Generated by Django 2.1.3 on 2018-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181126_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity_left',
            field=models.IntegerField(null=True),
        ),
    ]
