# Generated by Django 2.1.3 on 2018-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181127_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinecategory',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
