# Generated by Django 2.1.3 on 2018-11-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sale_salesinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MedicineCategory'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Medicine'),
        ),
    ]
