# Generated by Django 2.1.3 on 2018-11-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181127_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterIndexTogether(
            name='medicine',
            index_together={('id', 'slug')},
        ),
    ]
