# Generated by Django 2.1.3 on 2018-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sale_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
